### ISSUE TITLE
New sozi install cannot open 6-month-old presentation

### ISSUE THREAD

**Issue by bozito** [senshu/Sozi#233]
I upgraded from Ubuntu 12.04 to Ubuntu 14.04 and reinstalled inkscape/python-lxml/sozi and I cannot reopen a sozi presentation created last january (with Sozi 13.10-03192715) with my new install (Sozi 13.11-30213629).
lxml is throwing errors when opening sozi extension:

Traceback (most recent call last):
  File "sozi.py", line 54, in <module>
    effect.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 211, in affect
    self.parse()
  File "/usr/share/inkscape/extensions/inkex.py", line 139, in parse
    self.document = etree.parse(stream)
  File "lxml.etree.pyx", line 3239, in lxml.etree.parse (src/lxml/lxml.etree.c:69955)
  File "parser.pxi", line 1769, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:102257)
  File "parser.pxi", line 1789, in lxml.etree._parseFilelikeDocument (src/lxml/lxml.etree.c:102516)
  File "parser.pxi", line 1684, in lxml.etree._parseDocFromFilelike (src/lxml/lxml.etree.c:101442)
  File "parser.pxi", line 1134, in lxml.etree._BaseParser._parseDocFromFilelike (src/lxml/lxml.etree.c:97069)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91275)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92461)
  File "parser.pxi", line 622, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91757)
lxml.etree.XMLSyntaxError: internal error: Huge input lookup, line 13488, column 6031617

**Comment by IntraCherche** [comment]
Although the thread was closed, a different (maybe simpler) workaround worked for me (Ubuntu 14.04 and Sozi 13.11-30213629) and may help others. 

I faced the same problem with a 19 MB drawing. I DID NOT APPLY SENSHU'S TRICK.

Here are the steps that have been followed :

Indeed I selected nothing on my drawing, and then went to "File" | "Document Properties".
Here in "Page" tab I clicked on "Adjust page to drawing or selection". The page was adjusted.

Then I closed the properties window, saved the document (maybe not needed) and launched Sozi again, which worked as expected.

Sorry again for reopening this thread.

KR
